ci!: [UIP-6036]: publish astro alpha only
## Describe your changes
fix: `Error: Cannot find module '@commitlint/config-lerna-scopes'`

With yarn 2 plug-n-play tools like npx no longer know where to find external packages. To fix this we can either use yarn to run similar commands or require the .pnp file with: ;`NODE_OPTIONS="--require ./.pnp.cjs" `.

This replaces `npx commitlint` with `yarn commitlint`, which works locally.