feat: [UIP-7591] Add playground to astro and end user storybooks
## Describe your changes

## Issue Summary:
Rendering issues observed in complex components such as ArrayField, ListView, and Icon, where items are passed as children via mapping. These components do not render the mapped children as expected.
1. Items Not Rendering in CodeSandbox
Storybook code example:

```
export const Default = args => (
  <OverlayProvider>
    <ComboBoxField {...actions} {...args}>
      {item => <Item key={item.name} data-id={item.name}>{item.name}</Item>}
    </ComboBoxField>
  </OverlayProvider>
);
```
Upon opening the above example in CodeSandbox...
```
import { $f57aed4a881a3485$export$bf688221f59024e5, ComboBoxField } from '@pingux/astro';

export default App = () => {
return <$f57aed4a881a3485$export$bf688221f59024e5>
  <ComboBoxField
    defaultItems={[
      {
        id: '1',
        name: 'Aardvark'
      },
      {
        id: '2',
        name: 'Kangaroo'
      },
      {
        id: '3',
        name: 'Snake'
      }
    ]}
    disableKeys={[
      'Snake'
    ]}
    label="Example label"
    onBlur={() => {}}
    onFocus={() => {}}
    onFocusChange={() => {}}
    onInputChange={() => {}}
    onKeyDown={() => {}}
    onKeyUp={() => {}}
    onLoadMore={() => {}}
    onOpenChange={() => {}}
    onSelectionChange={() => {}}
  />
</$f57aed4a881a3485$export$bf688221f59024e5>;
}
```
After manually adding the Item as a child and replacing `$f57aed4a881a3485$export$bf688221f59024e5` with `OverlayProvider` in CodeSandbox, the component starts rendering correctly.
```
import { OverlayProvider, ComboBoxField, Item } from "@pingux/astro";

export default App = () => {
  return (
    <OverlayProvider>
      <ComboBoxField
        defaultItems={[
          {
            id: "1",
            name: "Aardvark",
          },
          {
            id: "2",
            name: "Kangaroo",
          },
          {
            id: "3",
            name: "Snake",
          },
        ]}
        disableKeys={["Snake"]}
        label="Example label"
        onBlur={() => {}}
        onFocus={() => {}}
        onFocusChange={() => {}}
        onInputChange={() => {}}
        onKeyDown={() => {}}
        onKeyUp={() => {}}
        onLoadMore={() => {}}
        onOpenChange={() => {}}
        onSelectionChange={() => {}}
      >
        {(item) => (
          <Item key={item.name} data-id={item.name}>
            {item.name}
          </Item>
        )}
      </ComboBoxField>
    </OverlayProvider>
  );
};
```
2. Icons Not Rendering Properly
In Storybook, icons render fine using:
```
<Icon icon={SearchIcon} title={{ name: 'Search Icon' }} />
In CodeSandbox,
<Icon
  color="active"
  icon={{
    $$typeof: Symbol(react.memo),
    compare: null,
    type: () => {}
  }}
  ...
/>
```
rendering fails with:
Error: Element type is invalid: expected a string or class/function but got: object.
Problematic icon prop in CodeSandbox:
```
icon={{
  $$typeof: Symbol(react.memo),
  compare: null,
  type: () => {}
}}
```
the icon prop is transformed into an invalid React element.

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have added tests for any new or fixed functionality to prevent regressions
- [ ] I have added clarifying code comments to blocks which other devs may have questions on

Closes UIP-7591